// Data for Anime section
window.sectionData = window.sectionData || {};
window.sectionData['Anime'] = {
  hasLight: false,
  maxPerPage: 8,
  dark: [
    { src: 'Anime//01.jpg', thumb: 'thumbnails/Anime/01.jpg', alt: '01.jpg' },
    { src: 'Anime//02.jpg', thumb: 'thumbnails/Anime/02.jpg', alt: '02.jpg' },
    { src: 'Anime//03.jpg', thumb: 'thumbnails/Anime/03.jpg', alt: '03.jpg' },
    { src: 'Anime//05.jpg', thumb: 'thumbnails/Anime/05.jpg', alt: '05.jpg' },
    { src: 'Anime//06.jpg', thumb: 'thumbnails/Anime/06.jpg', alt: '06.jpg' },
    { src: 'Anime//08.jpg', thumb: 'thumbnails/Anime/08.jpg', alt: '08.jpg' },
    { src: 'Anime//09.jpg', thumb: 'thumbnails/Anime/09.jpg', alt: '09.jpg' },
    { src: 'Anime//11.jpg', thumb: 'thumbnails/Anime/11.jpg', alt: '11.jpg' },
    { src: 'Anime//12.jpg', thumb: 'thumbnails/Anime/12.jpg', alt: '12.jpg' },
    { src: 'Anime//13.jpg', thumb: 'thumbnails/Anime/13.jpg', alt: '13.jpg' },
    { src: 'Anime//14.jpg', thumb: 'thumbnails/Anime/14.jpg', alt: '14.jpg' },
    { src: 'Anime//15.jpg', thumb: 'thumbnails/Anime/15.jpg', alt: '15.jpg' },
    { src: 'Anime//17.jpeg', thumb: 'thumbnails/Anime/17.jpeg', alt: '17.jpeg' },
    { src: 'Anime//18.jpeg', thumb: 'thumbnails/Anime/18.jpeg', alt: '18.jpeg' },
    { src: 'Anime//19.jpeg', thumb: 'thumbnails/Anime/19.jpeg', alt: '19.jpeg' },
    { src: 'Anime//21.jpeg', thumb: 'thumbnails/Anime/21.jpeg', alt: '21.jpeg' },
    { src: 'Anime//23.jpeg', thumb: 'thumbnails/Anime/23.jpeg', alt: '23.jpeg' },
    { src: 'Anime//24.jpeg', thumb: 'thumbnails/Anime/24.jpeg', alt: '24.jpeg' },
    { src: 'Anime//25.jpg', thumb: 'thumbnails/Anime/25.jpg', alt: '25.jpg' },
    { src: 'Anime//26.jpg', thumb: 'thumbnails/Anime/26.jpg', alt: '26.jpg' },
    { src: 'Anime//28.jpg', thumb: 'thumbnails/Anime/28.jpg', alt: '28.jpg' },
    { src: 'Anime//29.jpg', thumb: 'thumbnails/Anime/29.jpg', alt: '29.jpg' },
    { src: 'Anime//30.jpg', thumb: 'thumbnails/Anime/30.jpg', alt: '30.jpg' },
    { src: 'Anime//32.jpg', thumb: 'thumbnails/Anime/32.jpg', alt: '32.jpg' },
    { src: 'Anime//33.jpg', thumb: 'thumbnails/Anime/33.jpg', alt: '33.jpg' },
    { src: 'Anime//34.jpg', thumb: 'thumbnails/Anime/34.jpg', alt: '34.jpg' },
    { src: 'Anime//35.jpg', thumb: 'thumbnails/Anime/35.jpg', alt: '35.jpg' },
    { src: 'Anime//36.jpg', thumb: 'thumbnails/Anime/36.jpg', alt: '36.jpg' },
    { src: 'Anime//37.jpg', thumb: 'thumbnails/Anime/37.jpg', alt: '37.jpg' },
    { src: 'Anime//38.jpg', thumb: 'thumbnails/Anime/38.jpg', alt: '38.jpg' },
    { src: 'Anime//39.png', thumb: 'thumbnails/Anime/39.png', alt: '39.png' },
    { src: 'Anime//40.png', thumb: 'thumbnails/Anime/40.png', alt: '40.png' },
    { src: 'Anime//41.png', thumb: 'thumbnails/Anime/41.png', alt: '41.png' },
    { src: 'Anime//42.png', thumb: 'thumbnails/Anime/42.png', alt: '42.png' },
    { src: 'Anime//43.png', thumb: 'thumbnails/Anime/43.png', alt: '43.png' },
    { src: 'Anime//44.png', thumb: 'thumbnails/Anime/44.png', alt: '44.png' },
    { src: 'Anime//45.png', thumb: 'thumbnails/Anime/45.png', alt: '45.png' },
    { src: 'Anime//46.png', thumb: 'thumbnails/Anime/46.png', alt: '46.png' },
    { src: 'Anime//48.png', thumb: 'thumbnails/Anime/48.png', alt: '48.png' },
    { src: 'Anime//50.png', thumb: 'thumbnails/Anime/50.png', alt: '50.png' },
    { src: 'Anime//51.png', thumb: 'thumbnails/Anime/51.png', alt: '51.png' },
    { src: 'Anime//53.png', thumb: 'thumbnails/Anime/53.png', alt: '53.png' },
    { src: 'Anime//54.png', thumb: 'thumbnails/Anime/54.png', alt: '54.png' },
    { src: 'Anime//55.png', thumb: 'thumbnails/Anime/55.png', alt: '55.png' },
    { src: 'Anime//56.png', thumb: 'thumbnails/Anime/56.png', alt: '56.png' },
    { src: 'Anime//57.png', thumb: 'thumbnails/Anime/57.png', alt: '57.png' },
    { src: 'Anime//58.png', thumb: 'thumbnails/Anime/58.png', alt: '58.png' },
    { src: 'Anime//59.png', thumb: 'thumbnails/Anime/59.png', alt: '59.png' },
    { src: 'Anime//61.png', thumb: 'thumbnails/Anime/61.png', alt: '61.png' },
    { src: 'Anime//63.png', thumb: 'thumbnails/Anime/63.png', alt: '63.png' },
    { src: 'Anime//65.png', thumb: 'thumbnails/Anime/65.png', alt: '65.png' },
    { src: 'Anime//66.png', thumb: 'thumbnails/Anime/66.png', alt: '66.png' },
    { src: 'Anime//68.png', thumb: 'thumbnails/Anime/68.png', alt: '68.png' },
    { src: 'Anime//69.png', thumb: 'thumbnails/Anime/69.png', alt: '69.png' },
    { src: 'Anime//70.png', thumb: 'thumbnails/Anime/70.png', alt: '70.png' },
    { src: 'Anime//71.png', thumb: 'thumbnails/Anime/71.png', alt: '71.png' },
    { src: 'Anime//72.png', thumb: 'thumbnails/Anime/72.png', alt: '72.png' },
    { src: 'Anime//73.png', thumb: 'thumbnails/Anime/73.png', alt: '73.png' },
    { src: 'Anime//74.png', thumb: 'thumbnails/Anime/74.png', alt: '74.png' },
  ],
  light: []
};
