// Data for Atmospheric section
window.sectionData = window.sectionData || {};
window.sectionData['Atmospheric'] = {
  hasLight: false,
  maxPerPage: 8,
  dark: [
    { src: 'Atmospheric//01.jpg', thumb: 'Atmospheric//01.jpg', alt: '01.jpg' },
    { src: 'Atmospheric//02.jpg', thumb: 'Atmospheric//02.jpg', alt: '02.jpg' },
    { src: 'Atmospheric//03.jpg', thumb: 'Atmospheric//03.jpg', alt: '03.jpg' },
    { src: 'Atmospheric//04.jpg', thumb: 'Atmospheric//04.jpg', alt: '04.jpg' },
    { src: 'Atmospheric//05.jpg', thumb: 'Atmospheric//05.jpg', alt: '05.jpg' },
    { src: 'Atmospheric//06.jpeg', thumb: 'Atmospheric//06.jpeg', alt: '06.jpeg' },
    { src: 'Atmospheric//07.jpg', thumb: 'Atmospheric//07.jpg', alt: '07.jpg' },
    { src: 'Atmospheric//08.jpg', thumb: 'Atmospheric//08.jpg', alt: '08.jpg' },
    { src: 'Atmospheric//09.jpg', thumb: 'Atmospheric//09.jpg', alt: '09.jpg' },
    { src: 'Atmospheric//10.jpg', thumb: 'Atmospheric//10.jpg', alt: '10.jpg' },
    { src: 'Atmospheric//11.jpg', thumb: 'Atmospheric//11.jpg', alt: '11.jpg' },
    { src: 'Atmospheric//12.jpg', thumb: 'Atmospheric//12.jpg', alt: '12.jpg' },
    { src: 'Atmospheric//13.jpg', thumb: 'Atmospheric//13.jpg', alt: '13.jpg' },
    { src: 'Atmospheric//14.jpg', thumb: 'Atmospheric//14.jpg', alt: '14.jpg' },
    { src: 'Atmospheric//15.png', thumb: 'Atmospheric//15.png', alt: '15.png' },
    { src: 'Atmospheric//16.png', thumb: 'Atmospheric//16.png', alt: '16.png' },
    { src: 'Atmospheric//17.png', thumb: 'Atmospheric//17.png', alt: '17.png' },
    { src: 'Atmospheric//18.png', thumb: 'Atmospheric//18.png', alt: '18.png' },
    { src: 'Atmospheric//19.png', thumb: 'Atmospheric//19.png', alt: '19.png' },
    { src: 'Atmospheric//20.png', thumb: 'Atmospheric//20.png', alt: '20.png' },
    { src: 'Atmospheric//21.png', thumb: 'Atmospheric//21.png', alt: '21.png' },
    { src: 'Atmospheric//22.png', thumb: 'Atmospheric//22.png', alt: '22.png' },
    { src: 'Atmospheric//23.png', thumb: 'Atmospheric//23.png', alt: '23.png' },
    { src: 'Atmospheric//24.png', thumb: 'Atmospheric//24.png', alt: '24.png' },
    { src: 'Atmospheric//25.png', thumb: 'Atmospheric//25.png', alt: '25.png' },
    { src: 'Atmospheric//26.png', thumb: 'Atmospheric//26.png', alt: '26.png' },
    { src: 'Atmospheric//27.png', thumb: 'Atmospheric//27.png', alt: '27.png' },
    { src: 'Atmospheric//28.png', thumb: 'Atmospheric//28.png', alt: '28.png' },
    { src: 'Atmospheric//29.png', thumb: 'Atmospheric//29.png', alt: '29.png' },
    { src: 'Atmospheric//30.png', thumb: 'Atmospheric//30.png', alt: '30.png' },
    { src: 'Atmospheric//31.png', thumb: 'Atmospheric//31.png', alt: '31.png' },
    { src: 'Atmospheric//32.png', thumb: 'Atmospheric//32.png', alt: '32.png' },
    { src: 'Atmospheric//33.jpg', thumb: 'Atmospheric//33.jpg', alt: '33.jpg' },
  ],
  light: []
};
